name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt, clippy
    - uses: actions/checkout@master
    - name: Format
      run: |
        cargo fmt --all -- --check
    - name: Clippy
      run: |
        cargo clippy -- -D warnings
    - name: Clippy (disable_simd)
      run: |
        cargo clippy --features disable_simd -- -D warnings
