name: Test
on: [push, pull_request]
jobs:
  native:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose --workspace
